[workspace]
members = [
  "principal", # Codebase for principal / master nodes
  "worker",    # Codebase for worker nodes
  
]

[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true        # Enable link-time optimization.
codegen-units = 1 # Disable parallel codegen.
