[package]
name = "principal"
version = "0.1.0"
edition = "2021"
 workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.160"
serde_json = "1.0.96"
tokio = "1.28.0"
tonic = "0.9.2"
amiquip = "0.4"
