[package]
name = "worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.28.4"
tonic = { version = "0.9.2", features = ["tls", "prost"] }
tokio = { version = "1.27.0", features = ["full"] }
pcap = "1.0.0"
local-ip-address = "0.5.1"
